instead of adding the `SSH_AUTH_SOCK` env to `~/.bashrc` this step'll now expose it with `envman`

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -1,4 +1,4 @@
-format_version: 0.9.10
+format_version: 1.1.0
 default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
 
 app:
@@ -9,9 +9,94 @@ app:
 workflows:
   test:
     steps:
+    - change-workdir:
+        title: Switch working dir to test/_tmp dir
+        description: |-
+          To prevent step testing issues, like referencing relative
+          files with just './some-file', which would work for local tests
+          but not if the step is included in another bitrise.yml!
+        run_if: true
+        inputs:
+        - path: ./_tmp
+        - is_create_path: true
+    - script:
+        title: Remove SSH keys from agent
+        inputs:
+        - content: |-
+            #!/bin/bash
+            set -x
+            ssh-add -D
+            echo
     - path::./:
         run_if: true
         inputs:
         - ssh_rsa_private_key: $TEST_SSH_RSA_PRIVATE_KEY
         - ssh_key_save_path: "$HOME/.ssh/bitrise_step_activate_ssh_key"
         - is_remove_other_identities: "true"
+    - script:
+        title: Output check
+        inputs:
+        - content: |-
+            #!/bin/bash
+            set -e
+            if [ -z "$SSH_AUTH_SOCK" ] ; then
+              echo " [!] Missing: SSH_AUTH_SOCK"
+              exit 1
+            else
+              echo "-> SSH_AUTH_SOCK: $SSH_AUTH_SOCK"
+            fi
+    - script:
+        title: CI
+        inputs:
+        - content: |-
+            #!/bin/bash
+            set -e
+            set -x
+
+            bash ../_tests/test_ok.sh
+            bash ../_tests/test_wrong.sh
+
+
+  # ----------------------------------------------------------------
+  # --- workflows to Share this step into a Step Library
+  share-this-step:
+    envs:
+      # if you want to share this step into a StepLib
+      - MY_STEPLIB_REPO_FORK_GIT_URL:
+      - STEP_ID_IN_STEPLIB: activate-ssh-key
+      - STEP_GIT_VERION_TAG_TO_SHARE: 3.1.0
+      - STEP_GIT_CLONE_URL: https://github.com/bitrise-io/steps-activate-ssh-key.git
+    description: |-
+      If this is the first time you try to share a Step you should
+      first call: $ bitrise share
+
+      This will print you a guide, and information about how Step sharing
+      works. Please read it at least once!
+
+      As noted in the Step sharing guide you'll have to fork the
+      StepLib you want to share this step into. Once you're done with forking
+      the repository you should set your own fork's git clone URL
+      in the `.bitrise.secrets.yml` file, or here in the `envs` section,
+      as the value of the `MY_STEPLIB_REPO_FORK_GIT_URL` environment.
+
+      You're now ready to share this Step, just make sure that
+      the `STEP_ID_IN_STEPLIB` and `STEP_GIT_VERION_TAG_TO_SHARE`
+      environments are set to the desired values!
+
+      To share this Step into a StepLib you can just run: $ bitrise run share-this-step
+
+      Once it finishes the only thing left is to actually create a Pull Request,
+      the way described in the guide printed at the end of the process.
+    steps:
+    - script:
+        inputs:
+        - content: |-
+            #!/bin/bash
+            set -e
+            set -x
+
+            bitrise share start -c ${MY_STEPLIB_REPO_FORK_GIT_URL}
+
+            bitrise share create --stepid ${STEP_ID_IN_STEPLIB} --tag ${STEP_GIT_VERION_TAG_TO_SHARE} --git ${STEP_GIT_CLONE_URL}
+
+            bitrise share finish
