Check id private key exists on disk

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -97,12 +97,12 @@ workflows:
             #!/bin/bash
             set -x
             ssh-add -D
-            echo
+            envman add --key KEY_PATH --value "./testsave/bitrise_step_activate_ssh_key"
     - path::./:
         run_if: true
         inputs:
         - ssh_rsa_private_key: $SSH_RSA_PRIVATE_KEY
-        - ssh_key_save_path: "./testsave/bitrise_step_activate_ssh_key"
+        - ssh_key_save_path: "$KEY_PATH"
         - is_remove_other_identities: "true"
         - verbose: true
     - script:
@@ -114,6 +114,11 @@ workflows:
 
             echo "Loaded identities:"
             ssh-add -l
+
+            if [[ ! -f $KEY_PATH ]]; then 
+              echo "[!] Private key not found at path: $KEY_PATH"
+              exit 1
+            fi
 
             if [ -z "$SSH_AUTH_SOCK" ] ; then
               echo " [!] Missing: SSH_AUTH_SOCK"
